### ISSUE TITLE
duckdbfs Attribution

### ISSUE THREAD

**Issue by arthurgailes** [cboettig/duckdbfs#23]
Hello,

I've copied some of your code for opening datasets and cached_conn for my own package, [overtureR](https://github.com/arthurgailes/overtureR), which serves a narrower purpose. However, this will probably mean removing `duckdbfs` as an Imports dependency. 

How would you like to be properly credited? So far, I'm writing "The core code is copied from `duckdbfs`, which deserves all credit for the implementation". But I'm also happy to add you as a contributor to my package if you'd like.

I'll also continue to suggest duckdbfs, as I plan to write vignettes that will use its spatial_join, and tests against it.

Thanks for all your work here, I'd been really stuck on the internal connection problem.

**Comment by cboettig** [comment]
borrow whatever is useful, attribute however feels right for you.  This is really a simple package and the real kudos belongs to the amazing duckdb team for the magic there.  

Cool, please let me know how things go with your spatial_join, or feedback on the syntax. I know it's not quite matching the way sf writes joins, but this felt reasonably clean to me, and I've found spatial joins incredibly useful and very fast.  I'm so glad others find that useful and think that ability needs to be more widely shared.

(if you're doing spatial stuff in duckdb, I've recently found with point data at least, the h3 extension is amazing... )
