### ISSUE TITLE
support webR

### ISSUE THREAD

**Issue by seanbirchall** [cboettig/duckdbfs#24]
Great package thank you for making it.

Wonder if you've thought at all about supporting webR? George did a good write up about why httpfs doesn't work under webR https://github.com/duckdb/duckdb-r/issues/66. Maybe a smaller package with a specific use case like `duckdbfs` might be a good place to get started with this issue. I plan to start looking into implementing it soon... though I'm an R developer not JS... especially not TS or ES, but going to give it a try.

**Comment by cboettig** [comment]
Thanks for raising, that's a good question. The short answer is that this package doesn't really do very much, so if it's possible within duckdb itself, it should be possible here.  But this package still depends on the R package duckdb, so I don't see us being able to support anything on this end that's not already possible over there. 

From the thread you linked the situation sounds a bit complex, i.e. that urls work without having the extension loaded, but extensions cannot be loaded.  That raises more questions for me -- what about other functionality of httpfs extension, like s3:// or hf:// ?  The current design here is pretty extension-focused, e.g. making sure httpfs is loaded automatically when necessary, likewise for the spatial extension.  (I've been greatly enjoying the h3 extension recently too, though no utilities added here).  Anyway, it sounds like at very least we would need to avoid that.  

My general instinct is to wait until there's wasm support for extensions being handled by the native duckdb libraries.
